### ISSUE TITLE
Error Submitting Linear Regression Quiz

### ISSUE THREAD

**Issue by tyleranton** [udacity/dlnd-issue-reports#10]
Error:

{u'vm_time': 0.92454695701599121, u'stdout': u'', u'vm_creation_time': 5.9843063354492188e-05, u'test_results': [], u'stderr': u'Traceback (most recent call last):\n File "vm_main3.py", line 47, in \n import main\n File "/tmp/vmuser_deomexoaqv/main.py", line 2, in \n import aiMain\n File "/tmp/vmuser_deomexoaqv/aiMain.py", line 90, in \n print(check_steps())\n File "/tmp/vmuser_deomexoaqv/aiMain.py", line 85, in check_steps\n laos_OK, laos_message = check_laos()\n File "/tmp/vmuser_deomexoaqv/aiMain.py", line 66, in check_laos\n return True, "Well done, your prediction of a life expectancy" + laos_life_exp[0][0] + " is correct!"\nTypeError: ufunc \'add\' did not contain a loop with signature matching types dtype(\'<U47\') dtype(\'<U47\') dtype(\'<U47\')\n', u'exec_server_time': 0.92906904220581055, u'exec_status': u'error'}
Thank you for your submission!

**Comment by adarsh0806** [comment]
Yes we are fixing this now.

**Comment by tyleranton** [comment]
It is working now.

**Comment by joytafty** [comment]
I got file not found exception

**Comment by joytafty** [comment]
FileNotFoundError: File b'bmi_and_life_expentancy.csv' does not exist
Traceback (most recent call last):
  File "/tmp/vmuser_chekpdtgvd/gapminder1.py", line 8, in <module>
    bmi_life_data = read_csv('bmi_and_life_expentancy.csv')

**Comment by joytafty** [comment]
File Not Found exception, please fix: 

Here's what I did: 

```
import pandas as pd
bmi_life_data = pd.read_csv('./bmi_and_life_expentancy.csv')
```

Traceback (most recent call last):
  File "/tmp/vmuser_azggnjdggz/studentMain.py", line 148, in check_steps
    data, model, prediction = load_vars()
  File "/tmp/vmuser_azggnjdggz/studentMain.py", line 51, in load_vars
    from gapminder1 import bmi_life_data
  File "/tmp/vmuser_azggnjdggz/gapminder1.py", line 7, in <module>
    bmi_life_data = pd.read_csv('./bmi_and_life_expentancy.csv')
  File "/usr/local/lib/python3.4/dist-packages/pandas/io/parsers.py", line 646, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "/usr/local/lib/python3.4/dist-packages/pandas/io/parsers.py", line 389, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/usr/local/lib/python3.4/dist-packages/pandas/io/parsers.py", line 730, in __init__
    self._make_engine(self.engine)
  File "/usr/local/lib/python3.4/dist-packages/pandas/io/parsers.py", line 923, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "/usr/local/lib/python3.4/dist-packages/pandas/io/parsers.py", line 1390, in __init__
    self._reader = _parser.TextReader(src, **kwds)
  File "pandas/parser.pyx", line 373, in pandas.parser.TextReader.__cinit__ (pandas/parser.c:4025)
  File "pandas/parser.pyx", line 667, in pandas.parser.TextReader._setup_parser_source (pandas/parser.c:8031)
FileNotFoundError: File b'./bmi_and_life_expentancy.csv' does not exist
Traceback (most recent call last):
  File "/tmp/vmuser_azggnjdggz/gapminder1.py", line 7, in <module>
    bmi_life_data = pd.read_csv('./bmi_and_life_expentancy.csv')
  File "/usr/local/lib/python3.4/dist-packages/pandas/io/parsers.py", line 646, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "/usr/local/lib/python3.4/dist-packages/pandas/io/parsers.py", line 389, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/usr/local/lib/python3.4/dist-packages/pandas/io/parsers.py", line 730, in __init__
    self._make_engine(self.engine)
  File "/usr/local/lib/python3.4/dist-packages/pandas/io/parsers.py", line 923, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "/usr/local/lib/python3.4/dist-packages/pandas/io/parsers.py", line 1390, in __init__
    self._reader = _parser.TextReader(src, **kwds)
  File "pandas/parser.pyx", line 373, in pandas.parser.TextReader.__cinit__ (pandas/parser.c:4025)
  File "pandas/parser.pyx", line 667, in pandas.parser.TextReader._setup_parser_source (pandas/parser.c:8031)
FileNotFoundError: File b'./bmi_and_life_expentancy.csv' does not exist

FileNotFoundError: File b'./bmi_and_life_expentancy.csv' does not exist
None

**Comment by tyleranton** [comment]
You have a typo in the file name. 'expentancy' should be 'expectancy'

**Comment by joytafty** [comment]
resolved. Thanks
