### ISSUE TITLE
Error submitting quiz on Learning and Loss

### ISSUE THREAD

**Issue by tyleranton** [udacity/dlnd-issue-reports#107]
Link: https://classroom.udacity.com/nanodegrees/nd101/parts/2a9dba0b-28eb-4b0e-acfa-bdcf35680d90/modules/269a4aad-9025-4354-a0ea-2623e889540a/lessons/b6deebe4-7f78-4947-b2c6-fc660ca942fb/concepts/96656ffd-8c94-43f4-a962-8d44319f8c9f

Error:

```
File "/base/data/home/runtimes/python27_experiment/python27_dist/lib/python2.7/json/decoder.py", line 383, in raw_decode
    raise ValueError("No JSON object could be decoded")
  ValueError: No JSON object could be decoded
  Environment: {'executor_result': {u'vm_time': 0.18641304969787598, u'stdout': u'', u'vm_creation_time': 0.0019659996032714844, u'test_results': [], u'stderr': u'Traceback (most recent call last):\n  File "vm_main3.py", line 47, in \n    import main\n  File "/tmp/vmuser_zzdbydxqou/main.py", line 2, in \n    import aiMain\n  File "/tmp/vmuser_zzdbydxqou/aiMain.py", line 51\n    print json.dumps(result)\n             ^\nSyntaxError: invalid syntax\n', u'exec_server_time': 0.20125699043273926, u'exec_status': u'error'}, 'grade_result': {'comment': 'Thank you for your submission!', 'feedback': '', 'completed': None, 'test_results': [], 'bin_codes': [], 'correct': False}, 'executor_status': u'error'}
  Submission: {'_operation': 'REGRADE', u'nn.py': u'"""\nNOTE: Here we\'re using an Input node for more than a scalar.\nIn the case of weights and inputs the value of the Input node is\nactually a python list!\n\nIn general, there\'s no restriction on the values that can be passed to an Input node.\n"""\nfrom miniflow import *\n\ninputs, weights, bias = Input(), Input(), Input()\n\nf = Linear(inputs, weights, bias)\n\nfeed_dict = {\n    inputs: [6, 14, 3],\n    weights: [0.5, 0.25, 1.4],\n    bias: 2\n}\n\ngraph = topological_sort(feed_dict)\noutput = forward_pass(f, graph)\n\nprint(output) # should be 12.7 with this example', u'miniflow.py': u'"""\nWrite the Linear#forward method below!\n"""\nimport numpy as np\n\nclass Node:\n    def init(self, inbound_nodes=[]):\n        # Nodes from which this Node receives values\n        self.inbound_nodes = inbound_nodes\n        # Nodes to which this Node passes values\n        self.outbound_nodes = []\n        # A calculated value\n        self.value = None\n        # Add this node as an outbound node on its inputs.\n        for n in self.inbound_nodes:\n            n.outbound_nodes.append(self)\n\n    # These will be implemented in a subclass.\n    def forward(self):\n        """\n        Forward propagation.\n\n        Compute the output value based on inbound_nodes and\n        store the result in self.value.\n        """\n        raise NotImplemented\n\n\nclass Input(Node):\n    def init(self):\n        # An Input Node has no inbound nodes,\n        # so no need to pass anything to the Node instantiator\n        Node.init(self)\n\n        # NOTE: Input Node is the only Node where the value\n        # may be passed as an argument to forward().\n        #\n        # All other Node implementations should get the value\n        # of the previous nodes from self.inbound_nodes\n        #\n        # Example:\n        # val0 = self.inbound_nodes[0].value\n    def forward(self, value=None):\n        # Overwrite the value if one is passed in.\n        if value is not None:\n            self.value = value\n\n\nclass Linear(Node):\n    def init(self, inputs, weights, bias):\n        Node.init(self, [inputs, weights, bias])\n\n        # NOTE: The weights and bias properties here are not\n        # numbers, but rather references to other nodes.\n        # The weight and bias values are stored within the\n        # respective nodes.\n\n    def forward(self):\n        """\n        Set self.value to the value of the linear function output.\n\n        Your code goes here!\n        """\n        self.value = np.dot(self.inbound_nodes[0].value, self.inbound_nodes[1].value) + self.inbound_nodes[2].value\n\n\n\ndef topological_sort(feed_dict):\n    """\n    Sort the nodes in topological order using Kahn\'s Algorithm.\n\n    feed_dict: A dictionary where the key is a Input Node and the value is the respective value feed to that Node.\n\n    Returns a list of sorted nodes.\n    """\n\n    input_nodes = [n for n in feed_dict.keys()]\n\n    G = {}\n    nodes = [n for n in input_nodes]\n    while len(nodes) > 0:\n        n = nodes.pop(0)\n        if n not in G:\n            G[n] = {\'in\': set(), \'out\': set()}\n        for m in n.outbound_nodes:\n            if m not in G:\n                G[m] = {\'in\': set(), \'out\': set()}\n            G[n][\'out\'].add(m)\n            G[m][\'in\'].add(n)\n            nodes.append(m)\n\n    L = []\n    S = set(input_nodes)\n    while len(S) > 0:\n        n = S.pop()\n\n        if isinstance(n, Input):\n            n.value = feed_dict[n]\n\n        L.append(n)\n        for m in n.outbound_nodes:\n            G[n][\'out\'].remove(m)\n            G[m][\'in\'].remove(n)\n            # if no other incoming edges add to S\n            if len(G[m][\'in\']) == 0:\n                S.add(m)\n    return L\n\n\ndef forward_pass(output_node, sorted_nodes):\n    """\n    Performs a forward pass through a list of sorted nodes.\n\n    Arguments:\n\n        output_node: A node in the graph, should be the output node (have no outgoing edges).\n        sorted_nodes: A topologically sorted list of nodes.\n\n    Returns the output Node\'s value\n    """\n\n    for n in sorted_nodes:\n        n.forward()\n\n    return output_node.value\n'}
```

**Comment by tyleranton** [comment]
This is also happening on the next quiz, Linear Transform:

https://classroom.udacity.com/nanodegrees/nd101/parts/2a9dba0b-28eb-4b0e-acfa-bdcf35680d90/modules/269a4aad-9025-4354-a0ea-2623e889540a/lessons/b6deebe4-7f78-4947-b2c6-fc660ca942fb/concepts/2e5f4127-f226-4572-bbe6-8196e7dfabd5

**Comment by jg1141** [comment]
I'm seeing exact same issue on SUBMIT, with this code running successfully at input:
```
class Linear(Node):
    def __init__(self, inputs, weights, bias):
        Node.__init__(self, [inputs, weights, bias])

        # NOTE: The weights and bias properties here are not
        # numbers, but rather references to other nodes.
        # The weight and bias values are stored within the
        # respective nodes.

    def forward(self):
        """
        Set self.value to the value of the linear function output.

        Your code goes here!
        """
        inputs = self.inbound_nodes[0].value
        weights = self.inbound_nodes[1].value
        bias = self.inbound_nodes[2].value
        self.value = sum([input*weight for input, weight in zip(inputs,weights)]) + bias


```

**Comment by jg1141** [comment]
Also happening at `https://classroom.udacity.com/nanodegrees/nd101/parts/2a9dba0b-28eb-4b0e-acfa-bdcf35680d90/modules/269a4aad-9025-4354-a0ea-2623e889540a/lessons/b6deebe4-7f78-4947-b2c6-fc660ca942fb/concepts/ce4e18b2-2777-40ca-9514-c659ada3f09a`

where SUBMIT barfs up:
```
File "/base/data/home/runtimes/python27_experiment/python27_dist/lib/python2.7/json/decoder.py", line 383, in raw_decode
    raise ValueError("No JSON object could be decoded")
  ValueError: No JSON object could be decoded
  Environment: {'executor_result': {u'vm_time': 0.17168617248535156, u'stdout': u'EPOCH 0: Cost = 56565446.000, x = 15042.000\nEPOCH 1: Cost = 36201887.240, x = 12033.600\nEPOCH 2: Cost = 23169209.634, x = 9626.880\nEPOCH 3: Cost = 14828295.966, x = 7701.504\nEPOCH 4: Cost = 9490111.218, x = 6161.203\nEPOCH 5: Cost = 6073672.979, x = 4928.963\nEPOCH 6: Cost = 3887152.507, x = 3943.170\nEPOCH 7: Cost = 2487779.404, x = 3154.536\nEPOCH 8: Cost = 1592180.619, x = 2523.629\nEPOCH 9: Cost = 1018997.396, x = 2018.903\nEPOCH 10: Cost = 652160.133, x = 1615.122\nEPOCH 11: Cost = 417384.285, x = 1292.098\nEPOCH 12: Cost = 267127.743, x = 1033.678\nEPOCH 13: Cost = 170963.555, x = 826.943\nEPOCH 14: Cost = 109418.475, x = 661.554\nEPOCH 15: Cost = 70029.624, x = 529.243\nEPOCH 16: Cost = 44820.760, x = 423.395\nEPOCH 17: Cost = 28687.086, x = 338.716\nEPOCH 18: Cost = 18361.535, x = 270.973\nEPOCH 19: Cost = 11753.182, x = 216.778\nEPOCH 20: Cost = 7523.837, x = 173.422\nEPOCH 21: Cost = 4817.056, x = 138.738\nEPOCH 22: Cost = 3084.716, x = 110.990\nEPOCH 23: Cost = 1976.018, x = 88.792\nEPOCH 24: Cost = 1266.451, x = 71.034\nEPOCH 25: Cost = 812.329, x = 56.827\nEPOCH 26: Cost = 521.691, x = 45.462\nEPOCH 27: Cost = 335.682, x = 36.369\nEPOCH 28: Cost = 216.636, x = 29.095\nEPOCH 29: Cost = 140.447, x = 23.276\nEPOCH 30: Cost = 91.686, x = 18.621\nEPOCH 31: Cost = 60.479, x = 14.897\nEPOCH 32: Cost = 40.507, x = 11.918\nEPOCH 33: Cost = 27.724, x = 9.534\nEPOCH 34: Cost = 19.544, x = 7.627\nEPOCH 35: Cost = 14.308, x = 6.102\nEPOCH 36: Cost = 10.957, x = 4.881\nEPOCH 37: Cost = 8.813, x = 3.905\nEPOCH 38: Cost = 7.440, x = 3.124\nEPOCH 39: Cost = 6.562, x = 2.499\nEPOCH 40: Cost = 5.999, x = 1.999\nEPOCH 41: Cost = 5.640, x = 1.600\nEPOCH 42: Cost = 5.409, x = 1.280\nEPOCH 43: Cost = 5.262, x = 1.024\nEPOCH 44: Cost = 5.168, x = 0.819\nEPOCH 45: Cost = 5.107, x = 0.655\nEPOCH 46: Cost = 5.069, x = 0.524\nEPOCH 47: Cost = 5.044, x = 0.419\nEPOCH 48: Cost = 5.028, x = 0.335\nEPOCH 49: Cost = 5.018, x = 0.268\nEPOCH 50: Cost = 5.012, x = 0.215\nEPOCH 51: Cost = 5.007, x = 0.172\nEPOCH 52: Cost = 5.005, x = 0.137\nEPOCH 53: Cost = 5.003, x = 0.110\nEPOCH 54: Cost = 5.002, x = 0.088\nEPOCH 55: Cost = 5.001, x = 0.070\nEPOCH 56: Cost = 5.001, x = 0.056\nEPOCH 57: Cost = 5.001, x = 0.045\nEPOCH 58: Cost = 5.000, x = 0.036\nEPOCH 59: Cost = 5.000, x = 0.029\nEPOCH 60: Cost = 5.000, x = 0.023\nEPOCH 61: Cost = 5.000, x = 0.018\nEPOCH 62: Cost = 5.000, x = 0.015\nEPOCH 63: Cost = 5.000, x = 0.012\nEPOCH 64: Cost = 5.000, x = 0.009\nEPOCH 65: Cost = 5.000, x = 0.008\nEPOCH 66: Cost = 5.000, x = 0.006\nEPOCH 67: Cost = 5.000, x = 0.005\nEPOCH 68: Cost = 5.000, x = 0.004\nEPOCH 69: Cost = 5.000, x = 0.003\nEPOCH 70: Cost = 5.000, x = 0.002\nEPOCH 71: Cost = 5.000, x = 0.002\nEPOCH 72: Cost = 5.000, x = 0.002\nEPOCH 73: Cost = 5.000, x = 0.001\nEPOCH 74: Cost = 5.000, x = 0.001\nEPOCH 75: Cost = 5.000, x = 0.001\nEPOCH 76: Cost = 5.000, x = 0.001\nEPOCH 77: Cost = 5.000, x = 0.001\nEPOCH 78: Cost = 5.000, x = 0.000\nEPOCH 79: Cost = 5.000, x = 0.000\nEPOCH 80: Cost = 5.000, x = 0.000\nEPOCH 81: Cost = 5.000, x = 0.000\nEPOCH 82: Cost = 5.000, x = 0.000\nEPOCH 83: Cost = 5.000, x = 0.000\nEPOCH 84: Cost = 5.000, x = 0.000\nEPOCH 85: Cost = 5.000, x = 0.000\nEPOCH 86: Cost = 5.000, x = 0.000\nEPOCH 87: Cost = 5.000, x = 0.000\nEPOCH 88: Cost = 5.000, x = 0.000\nEPOCH 89: Cost = 5.000, x = 0.000\nEPOCH 90: Cost = 5.000, x = 0.000\nEPOCH 91: Cost = 5.000, x = 0.000\nEPOCH 92: Cost = 5.000, x = 0.000\nEPOCH 93: Cost = 5.000, x = 0.000\nEPOCH 94: Cost = 5.000, x = 0.000\nEPOCH 95: Cost = 5.000, x = 0.000\nEPOCH 96: Cost = 5.000, x = 0.000\nEPOCH 97: Cost = 5.000, x = 0.000\nEPOCH 98: Cost = 5.000, x = 0.000\nEPOCH 99: Cost = 5.000, x = 0.000\nEPOCH 100: Cost = 5.000, x = 0.000\n{"is_correct": true, "output": "", "values": [], "error": false}\n', u'vm_creation_time': 6.7949295043945312e-05, u'test_results': [], u'stderr': u'', u'exec_server_time': 0.1746058464050293, u'exec_status': u'ok'}, 'grade_result': {'comment': 'Thank you for your submission!', 'feedback': '', 'completed': None, 'test_results': [], 'bin_codes': [], 'correct': False}, 'executor_status': u'ok'}
  Submission: {'_operation': 'REGRADE', u'f.py': u'"""\nGiven the starting point of any x gradient descent\nshould be able to find the minimum value of x for the\ncost function f defined below.\n"""\nimport random\nfrom gd import gradient_descent_update\n\n\ndef f(x):\n    """\n    Quadratic function.\n\n    It\'s easy to see the minimum value of the function\n    is 5 when is x=0.\n    """\n    return x*2 + 5\n\n\ndef df(x):\n    """\n    Derivative of f with respect to x.\n    """\n    return 2x\n\n\n# Random number better 0 and 10,000. Feel free to set x whatever you like.\nx = random.randint(0, 10000)\n# TODO: Set the learning rate\nlearning_rate = 0.1\nepochs = 100\n\nfor i in range(epochs+1):\n    cost = f(x)\n    gradx = df(x)\n    print("EPOCH {}: Cost = {:.3f}, x = {:.3f}".format(i, cost, gradx))\n    x = gradient_descent_update(x, gradx, learning_rate)\n', u'gd.py': u'def gradient_descent_update(x, gradx, learning_rate):\n    """\n    Performs a gradient descent update.\n    """\n    # TODO: Implement gradient descent.\n    \n    # Return the new value for x\n    return x - learning_rate * gradx\nimport f'}
```
