### ISSUE TITLE
Bug in code for Convolutional Network in TF

### ISSUE THREAD

**Issue by kulshekhar** [udacity/dlnd-issue-reports#163]
In Lesson 19, section 30, the code shown in the section fails with the following message:

```
Traceback (most recent call last):
  File "filename.py", line 76, in <module>
    cost = tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits(logits, y))
  File "/home/user/anaconda3/envs/tensorflow/lib/python3.5/site-packages/tensorflow/python/ops/nn_ops.py", line 1578, in softmax_cross_entropy_with_logits
    labels, logits)
  File "/home/user/anaconda3/envs/tensorflow/lib/python3.5/site-packages/tensorflow/python/ops/nn_ops.py", line 1533, in _ensure_xent_args
    "named arguments (labels=..., logits=..., ...)" % name)
ValueError: Only call `softmax_cross_entropy_with_logits` with named arguments (labels=..., logits=..., ...)
```

In the code, replacing

```python
cost = tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits(logits, y))
```

with 

```python
cost = tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits(logits=logits, labels=y))
```

solves the issue. Note that this issue isn't present in the code from the download link.

**Comment by clapollo** [comment]
Yep. The old version used to work but TF 1.0 requires the argument names. Fixed.
