### ISSUE TITLE
Tensorflow Quizzes of Lesson 9

### ISSUE THREAD

**Issue by rahul-ahuja** [udacity/dlnd-issue-reports#436]
1.
Refer to Lesson 9: Tensorflow; section 7 Quiz Tensorflow softmax

When running the quiz solution as it is, I get the following error;

```
Traceback (most recent call last):
  File "all.py", line 30, in <module>
    from quiz_test import get_result
  File "/tmp/vmuser_rnpitvylum/quiz_test.py", line 15
    tente:
         ^
SyntaxError: invalid syntax
```

2.

Refer to Lesson 9: Tensorflow; section 5 Quiz Tensorflow Math

When I test my submission on 5. Quiz Tensorflow Math, I get a correct print output. When I submit, I get the below error. When I try just pasting the solution from solution.py, I get the same output:

```
    File "/base/alloc/tmpfs/dynamic_runtimes/python27/54c5883f70296ec8_unzipped/python27_dist/lib/python2.7/json/decoder.py", line 382, in raw_decode
        raise ValueError("No JSON object could be decoded")
      ValueError: No JSON object could be decoded
      Environment: {'executor_result': {u'vm_time': 0.12252092361450195, u'stdout': u'', u'vm_creation_time': 8.5115432739257812e-05, u'test_results': [], u'stderr': u'Traceback (most recent call last):\n  File "vm_main3.py", line 47, in \n    import main\n  File "/tmp/vmuser_uqteqdaxmx/main.py", line 2, in \n    import aiMain\n  File "/tmp/vmuser_uqteqdaxmx/aiMain.py", line 2, in \n    from quiz_test import get_result\n  File "/tmp/vmuser_uqteqdaxmx/quiz_test.py", line 15\n    tente:\n         ^\nSyntaxError: invalid syntax\n', u'exec_server_time': 0.12659502029418945, u'exec_status': u'error'}, 'grade_result': {'comment': 'Thank you for your submission!', 'feedback': '', 'completed': None, 'test_results': [], 'bin_codes': [], 'correct': False}, 'executor_status': u'error'}
      Submission: {'_operation': 'REGRADE', u'quiz.py': u'# Solution is available in the other "solution.py" tab\nimport tensorflow as tf\n\n# TODO: Convert the following to TensorFlow:\nx = 10\ny = 2\nz = x/y - 1\n\n# TODO: Print z from a session\n\na = tf.Variable(0.0)\nb = tf.Variable(0.0)\nc = tf.Variable(0.0)\n\nres = tf.cast(tf.subtract(tf.divide(a, b),c),tf.int32)\n\nwith tf.Session() as s:\n    output = s.run(res, feed_dict={a:10,b:2,c:-1})\n    \n    print(output)\n', u'solution.py': u"# Quiz Solution\n# Note: You can't run code in this tab\nimport tensorflow as tf\n\n# TODO: Convert the following to TensorFlow:\nx = tf.constant(10)\ny = tf.constant(2)\nz = tf.subtract(tf.divide(x,y),tf.cast(tf.constant(1), tf.float64))\n\n# TODO: Print z from a session\nwith tf.Session() as sess:\n    output = sess.run(z)\n    print(output)\n"}
```

3.

On the 4th section, "Tensorflow Input", no matter what I run (even if I delete everything and run "print('hello')", I receive the following error:

```
    Traceback (most recent call last):
      File "vm_main.py", line 33, in <module>
        import main
      File "/tmp/vmuser_lndyphuwue/main.py", line 2, in <module>
        import studentMain
      File "/tmp/vmuser_lndyphuwue/studentMain.py", line 1, in <module>
        from all import run_python3_shell
      File "/tmp/vmuser_lndyphuwue/all.py", line 17
    SyntaxError: Non-ASCII character '\xc3' in file /tmp/vmuser_lndyphuwue/all.py on line 17, but no encoding declared; see http://www.python.org/peps/pep-0263.html for details
```

**Comment by lcrucks** [comment]
Internal ticket: https://udacity.atlassian.net/browse/DLAND-16

**Comment by lcrucks** [comment]
Duplicate: ![Untitled.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/588b9ba628c7741a00ff4082/125516c66e82c728ace21e0d46dd9a8e2a968fac8babf301b44fff9e2c4533317346f67328dde57ce61b7a005c574cf9470c5f45fdaf8122a3b22e6c981e5ab38532022d8c6853beb2901eb80bbb258a4981b1bb8d4ac2eb3f24f5c6.png)
