### ISSUE TITLE
Replay buffer solution error

### ISSUE THREAD

**Issue by ablacklama** [udacity/dlnd-issue-reports#515]
The replay buffer example solution in the quadcopter lesson is giving me an error: Traceback (most recent call last):
  File "vm_main3.py", line 47, in <module>
    import main
  File "/tmp/vmuser_unwpsfzrbf/main.py", line 2, in <module>
    import studentMain
  File "/tmp/vmuser_unwpsfzrbf/studentMain.py", line 3, in <module>
    test_run()
  File "/tmp/vmuser_unwpsfzrbf/replay_buffer.py", line 50, in test_run
    print("\nRandom batch: size =", len(batch))  # maximum size if full
TypeError: object of type 'NoneType' has no len()
Replay buffer: size = 0

**Comment by Ortalarel** [comment]
Thank you for the comments. For issues of these nature please use our slack group and forums.
