### ISSUE TITLE
style transfer error Windows

### ISSUE THREAD

**Issue by lcrucks** [udacity/dlnd-issue-reports#595]
I followed the installation instructions for Windows and didn't get anywhere. When I tried to run evaluate.py script I first got an error message about moviepy module not installed. I tried to install it and now I get another message: "AttributeError: module 'scipy.misc' has no attribute 'imread'". 
Looks like the course script have not been tested in a while and got outdated.

I attach command window log for your reference.

(base) C:\Users\Xenon>conda create -n style-transfer python=3.5
Solving environment: done

## Package Plan ##

  environment location: C:\Users\Xenon\Miniconda3\envs\style-transfer

  added / updated specs:
    - python=3.5

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    certifi-2018.4.16          |           py35_0         143 KB
    setuptools-39.2.0          |           py35_0         593 KB
    pip-10.0.1                 |           py35_0         1.8 MB
    python-3.5.5               |       h0c2934d_2        18.2 MB
    wincertstore-0.2           |   py35hfebbdb8_0          13 KB
    wheel-0.31.1               |           py35_0          81 KB
    ------------------------------------------------------------
                                           Total:        20.8 MB

The following NEW packages will be INSTALLED:

    certifi:        2018.4.16-py35_0
    pip:            10.0.1-py35_0
    python:         3.5.5-h0c2934d_2
    setuptools:     39.2.0-py35_0
    vc:             14-h0510ff6_3
    vs2015_runtime: 14.0.25123-3
    wheel:          0.31.1-py35_0
    wincertstore:   0.2-py35hfebbdb8_0

Proceed ([y]/n)? y

Downloading and Extracting Packages
certifi-2018.4.16    |  143 KB | ###################################### | 100%
setuptools-39.2.0    |  593 KB | ###################################### | 100%
pip-10.0.1           |  1.8 MB | ###################################### | 100%
python-3.5.5         | 18.2 MB | ###################################### | 100%
wincertstore-0.2     |   13 KB | ###################################### | 100%
wheel-0.31.1         |   81 KB | ###################################### | 100%
Preparing transaction: done
Verifying transaction: done
Executing transaction: done
#
# To activate this environment, use
#
#     $ conda activate style-transfer
#
# To deactivate an active environment, use
#
#     $ conda deactivate

(base) C:\Users\Xenon>activate style-transfer

(style-transfer) C:\Users\Xenon>pip install tensorflow
Collecting tensorflow
  Downloading https://files.pythonhosted.org/packages/3f/bb/dd01844cf88d15264d92
e12a8b89526e1d805c082b8e945b632d4a1989a4/tensorflow-1.8.0-cp35-cp35m-win_amd64.w
hl (34.4MB)
    100% |################################| 34.4MB 297kB/s
Collecting gast>=0.2.0 (from tensorflow)
  Using cached https://files.pythonhosted.org/packages/5c/78/ff794fcae2ce8aa6323
e789d1f8b3b7765f601e7702726f430e814822b96/gast-0.2.0.tar.gz
Requirement already satisfied: wheel>=0.26 in c:\users\xenon\miniconda3\envs\sty
le-transfer\lib\site-packages (from tensorflow) (0.31.1)
Collecting astor>=0.6.0 (from tensorflow)
  Using cached https://files.pythonhosted.org/packages/b2/91/cc9805f1ff7b49f6201
36b3a7ca26f6a1be2ed424606804b0fbcf499f712/astor-0.6.2-py2.py3-none-any.whl
Collecting termcolor>=1.1.0 (from tensorflow)
  Using cached https://files.pythonhosted.org/packages/8a/48/a76be51647d0eb9f10e
2a4511bf3ffb8cc1e6b14e9e4fab46173aa79f981/termcolor-1.1.0.tar.gz
Collecting six>=1.10.0 (from tensorflow)
  Using cached https://files.pythonhosted.org/packages/67/4b/141a581104b1f6397bf
a78ac9d43d8ad29a7ca43ea90a2d863fe3056e86a/six-1.11.0-py2.py3-none-any.whl
Collecting grpcio>=1.8.6 (from tensorflow)
  Downloading https://files.pythonhosted.org/packages/0d/33/22ad4a9dcefe330180cd
b2d24fdd980af2a7a2dc03af208a408fd48195e0/grpcio-1.12.1-cp35-cp35m-win_amd64.whl
(1.4MB)
    100% |################################| 1.4MB 3.8MB/s
Collecting tensorboard<1.9.0,>=1.8.0 (from tensorflow)
  Using cached https://files.pythonhosted.org/packages/59/a6/0ae6092b7542cfedba6
b2a1c9b8dceaf278238c39484f3ba03b03f07803c/tensorboard-1.8.0-py3-none-any.whl
Collecting numpy>=1.13.3 (from tensorflow)
  Downloading https://files.pythonhosted.org/packages/f3/71/94628784c3f07d4bc0dd
38f8753e3f751d66cfd5a6823591179608c27f09/numpy-1.14.5-cp35-none-win_amd64.whl (1
3.4MB)
    100% |################################| 13.4MB 1.6MB/s
Collecting protobuf>=3.4.0 (from tensorflow)
  Downloading https://files.pythonhosted.org/packages/f0/7d/1145805ef3ac475074f8
d14d1c0512a79ef709ddfd35ca89c5fa4fc94065/protobuf-3.6.0-cp35-cp35m-win_amd64.whl
 (1.1MB)
    100% |################################| 1.1MB 2.3MB/s
Collecting absl-py>=0.1.6 (from tensorflow)
  Using cached https://files.pythonhosted.org/packages/57/8d/6664518f9b6ced0aa41
cf50b989740909261d4c212557400c48e5cda0804/absl-py-0.2.2.tar.gz
Collecting markdown>=2.6.8 (from tensorboard<1.9.0,>=1.8.0->tensorflow)
  Using cached https://files.pythonhosted.org/packages/6d/7d/488b90f470b96531a3f
5788cf12a93332f543dbab13c423a5e7ce96a0493/Markdown-2.6.11-py2.py3-none-any.whl
Collecting werkzeug>=0.11.10 (from tensorboard<1.9.0,>=1.8.0->tensorflow)
  Using cached https://files.pythonhosted.org/packages/20/c4/12e3e56473e52375aa2
9c4764e70d1b8f3efa6682bef8d0aae04fe335243/Werkzeug-0.14.1-py2.py3-none-any.whl
Collecting bleach==1.5.0 (from tensorboard<1.9.0,>=1.8.0->tensorflow)
  Using cached https://files.pythonhosted.org/packages/33/70/86c5fec937ea4964184
d4d6c4f0b9551564f821e1c3575907639036d9b90/bleach-1.5.0-py2.py3-none-any.whl
Collecting html5lib==0.9999999 (from tensorboard<1.9.0,>=1.8.0->tensorflow)
  Using cached https://files.pythonhosted.org/packages/ae/ae/bcb60402c60932b32df
af19bb53870b29eda2cd17551ba5639219fb5ebf9/html5lib-0.9999999.tar.gz
Requirement already satisfied: setuptools in c:\users\xenon\miniconda3\envs\styl
e-transfer\lib\site-packages (from protobuf>=3.4.0->tensorflow) (39.2.0)
Building wheels for collected packages: gast, termcolor, absl-py, html5lib
  Running setup.py bdist_wheel for gast ... done
  Stored in directory: C:\Users\Xenon\AppData\Local\pip\Cache\wheels\9a\1f\0e\3c
de98113222b853e98fc0a8e9924480a3e25f1b4008cedb4f
  Running setup.py bdist_wheel for termcolor ... done
  Stored in directory: C:\Users\Xenon\AppData\Local\pip\Cache\wheels\7c\06\54\bc
84598ba1daf8f970247f550b175aaaee85f68b4b0c5ab2c6
  Running setup.py bdist_wheel for absl-py ... done
  Stored in directory: C:\Users\Xenon\AppData\Local\pip\Cache\wheels\a0\f8\e9\19
33dbb3447ea6ef57062fd5461cb118deb8c2ed074e8344bf
  Running setup.py bdist_wheel for html5lib ... done
  Stored in directory: C:\Users\Xenon\AppData\Local\pip\Cache\wheels\50\ae\f9\d2
b189788efcf61d1ee0e36045476735c838898eef1cad6e29
Successfully built gast termcolor absl-py html5lib
Installing collected packages: gast, astor, termcolor, six, grpcio, markdown, nu
mpy, werkzeug, html5lib, bleach, protobuf, tensorboard, absl-py, tensorflow
Successfully installed absl-py-0.2.2 astor-0.6.2 bleach-1.5.0 gast-0.2.0 grpcio-
1.12.1 html5lib-0.9999999 markdown-2.6.11 numpy-1.14.5 protobuf-3.6.0 six-1.11.0
 tensorboard-1.8.0 tensorflow-1.8.0 termcolor-1.1.0 werkzeug-0.14.1

(style-transfer) C:\Users\Xenon>conda install scipy pillow
Solving environment: done

## Package Plan ##

  environment location: C:\Users\Xenon\Miniconda3\envs\style-transfer

  added / updated specs:
    - pillow
    - scipy

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    olefile-0.45.1             |           py35_0          47 KB
    mkl_random-1.0.1           |   py35h9258bd6_0         258 KB
    numpy-1.14.5               |   py35h9fa60d3_0          94 KB
    numpy-base-1.14.5          |   py35h5c71026_0         3.8 MB
    mkl_fft-1.0.1              |   py35h452e1ab_0         112 KB
    scipy-1.1.0                |   py35h672f292_0        13.5 MB
    pillow-5.1.0               |   py35h0738816_0         646 KB
    ------------------------------------------------------------
                                           Total:        18.4 MB

The following NEW packages will be INSTALLED:

    blas:         1.0-mkl
    freetype:     2.8-h51f8f2c_1
    icc_rt:       2017.0.4-h97af966_0
    intel-openmp: 2018.0.3-0
    jpeg:         9b-hb83a4c4_2
    libpng:       1.6.34-h79bbb47_0
    libtiff:      4.0.9-hb8ad9f9_1
    mkl:          2018.0.3-1
    mkl_fft:      1.0.1-py35h452e1ab_0
    mkl_random:   1.0.1-py35h9258bd6_0
    numpy:        1.14.5-py35h9fa60d3_0
    numpy-base:   1.14.5-py35h5c71026_0
    olefile:      0.45.1-py35_0
    pillow:       5.1.0-py35h0738816_0
    scipy:        1.1.0-py35h672f292_0
    tk:           8.6.7-hcb92d03_3
    zlib:         1.2.11-h8395fce_2

Proceed ([y]/n)? y

Downloading and Extracting Packages
olefile-0.45.1       |   47 KB | ###################################### | 100%
mkl_random-1.0.1     |  258 KB | ###################################### | 100%
numpy-1.14.5         |   94 KB | ###################################### | 100%
numpy-base-1.14.5    |  3.8 MB | ###################################### | 100%
mkl_fft-1.0.1        |  112 KB | ###################################### | 100%
scipy-1.1.0          | 13.5 MB | ###################################### | 100%
pillow-5.1.0         |  646 KB | ###################################### | 100%
Preparing transaction: done
Verifying transaction: done
Executing transaction: done

(style-transfer) C:\Users\Xenon>cd documents

(style-transfer) C:\Users\Xenon\Documents>cd python

(style-transfer) C:\Users\Xenon\Documents\Python>cd fast-style-transfer-master

(style-transfer) C:\Users\Xenon\Documents\Python\fast-style-transfer-master>pyth
on evaluate.py --checkpoint ./rain-princess.ckpt --inpath ./Millhouse.png --outp
ath ./output_image.jpg
Traceback (most recent call last):
  File "evaluate.py", line 14, in <module>
    from moviepy.video.io.VideoFileClip import VideoFileClip
ImportError: No module named 'moviepy'

(style-transfer) C:\Users\Xenon\Documents\Python\fast-style-transfer-master>cond
a install -c conda-forge moviepy
Solving environment: done

## Package Plan ##

  environment location: C:\Users\Xenon\Miniconda3\envs\style-transfer

  added / updated specs:
    - moviepy

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    moviepy-0.2.3.5            |             py_0          81 KB  conda-forge
    decorator-4.3.0            |             py_0          10 KB  conda-forge
    tqdm-4.23.4                |             py_0          35 KB  conda-forge
    imageio-2.3.0              |           py35_0         3.3 MB  conda-forge
    certifi-2018.4.16          |           py35_0         143 KB  conda-forge
    ------------------------------------------------------------
                                           Total:         3.5 MB

The following NEW packages will be INSTALLED:

    decorator: 4.3.0-py_0        conda-forge
    ffmpeg:    4.0-hf48ec3a_0    conda-forge
    imageio:   2.3.0-py35_0      conda-forge
    moviepy:   0.2.3.5-py_0      conda-forge
    tqdm:      4.23.4-py_0       conda-forge

The following packages will be UPDATED:

    certifi:   2018.4.16-py35_0              --> 2018.4.16-py35_0 conda-forge
    freetype:  2.8-h51f8f2c_1                --> 2.8.1-vc14_0     conda-forge [v
c14]
    jpeg:      9b-hb83a4c4_2                 --> 9b-vc14_2        conda-forge [v
c14]
    libpng:    1.6.34-h79bbb47_0             --> 1.6.34-vc14_0    conda-forge [v
c14]

The following packages will be DOWNGRADED:

    libtiff:   4.0.9-hb8ad9f9_1              --> 4.0.9-vc14_0     conda-forge [v
c14]
    tk:        8.6.7-hcb92d03_3              --> 8.6.7-vc14_0     conda-forge [v
c14]
    zlib:      1.2.11-h8395fce_2             --> 1.2.11-vc14_0    conda-forge [v
c14]

Proceed ([y]/n)? y

Downloading and Extracting Packages
moviepy-0.2.3.5      |   81 KB | ###################################### | 100%
decorator-4.3.0      |   10 KB | ###################################### | 100%
tqdm-4.23.4          |   35 KB | ###################################### | 100%
imageio-2.3.0        |  3.3 MB | ###################################### | 100%
certifi-2018.4.16    |  143 KB | ###################################### | 100%
Preparing transaction: done
Verifying transaction: done
Executing transaction: done

(style-transfer) C:\Users\Xenon\Documents\Python\fast-style-transfer-master>pyth
on evaluate.py --checkpoint ./rain-princess.ckpt --inpath ./Millhouse.png --outp
ath ./output_image.jpg
usage: evaluate.py [-h] --checkpoint CHECKPOINT --in-path IN_PATH --out-path
                   OUT_PATH [--device DEVICE] [--batch-size BATCH_SIZE]
                   [--allow-different-dimensions]
evaluate.py: error: the following arguments are required: --in-path, --out-path

(style-transfer) C:\Users\Xenon\Documents\Python\fast-style-transfer-master>pyth
on evaluate.py --checkpoint ./rain-princess.ckpt --in-path ./Millhouse.png --out
-path ./output_image.jpg
Traceback (most recent call last):
  File "evaluate.py", line 212, in <module>
    main()
  File "evaluate.py", line 199, in main
    device=opts.device)
  File "evaluate.py", line 132, in ffwd_to_img
    ffwd(paths_in, paths_out, checkpoint_dir, batch_size=1, device_t=device)
  File "evaluate.py", line 77, in ffwd
    img_shape = get_img(data_in[0]).shape
  File "src\utils.py", line 16, in get_img
    img = scipy.misc.imread(src, mode='RGB') # misc.imresize(, (256, 256, 3))
AttributeError: module 'scipy.misc' has no attribute 'imread'

(style-transfer) C:\Users\Xenon\Documents\Python\fast-style-transfer-master>

**Comment by Finemechanic** [comment]
As it was me who actually found this issue, I attach the log in a readable format.
[Udacity error.zip](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5b351732f4a0d300122eac15/125516c66e82c728ace21e0d46dd909b208b97b0cfecad51ab4fb2d86b56357c2301a03f32dfa17de71a23075b5647fd105b5746a9ffdd2ba7b76a7883590fffcd7f1d2598694ef1e1c84afd13b0328a488fb7b9894cc2e83b26e38a8c463e0c48.zip)
