### ISSUE TITLE
Issue submitting first quiz

### ISSUE THREAD

**Issue by erip** [udacity/dlnd-issue-reports#7]

**Comment by erip** [comment]
I just attempted to submit my first quiz solution after successfully testing it. I got the following error:

```
{u'vm_time': 2.6957519054412842, u'stdout': u' Country Life expectancy BMI\n0 Afghanistan 52.8 20.62058\n1 Albania 76.8 26.44657\n2 Algeria 75.5 24.59620\n3 Andorra 84.6 27.63048\n4 Angola 56.7 22.25083\n', u'vm_creation_time': 7.9870223999023438e-05, u'test_results': [], u'stderr': u'Traceback (most recent call last):\n File "vm_main3.py", line 47, in \n import main\n File "/tmp/vmuser_nmcodxbjpo/main.py", line 2, in \n import aiMain\n File "/tmp/vmuser_nmcodxbjpo/aiMain.py", line 90, in \n print(check_steps())\n File "/tmp/vmuser_nmcodxbjpo/aiMain.py", line 85, in check_steps\n laos_OK, laos_message = check_laos()\n File "/tmp/vmuser_nmcodxbjpo/aiMain.py", line 66, in check_laos\n return True, "Well done, your prediction of a life expectancy" + laos_life_exp[0][0] + " is correct!"\nTypeError: ufunc \'add\' did not contain a loop with signature matching types dtype(\'<U47\') dtype(\'<U47\') dtype(\'<U47\')\n', u'exec_server_time': 2.7010788917541504, u'exec_status': u'error'}
```

Is this an error with my code or is this an issue with the submission server?

**Comment by adarsh0806** [comment]
What kind of issue?

**Comment by adarsh0806** [comment]
Can you give the link to the quiz?

**Comment by erip** [comment]
[Here](https://classroom.udacity.com/nanodegrees/nd101/parts/2a9dba0b-28eb-4b0e-acfa-bdcf35680d90/modules/1ac82f5d-e14d-4feb-94e7-405d1558b4d0/lessons/22c76bdf-836e-4a99-a81b-43def2579c6d/concepts/18e56579-b33e-4159-be5d-ae36615c8b38#) is the link.

**Comment by sY9sE33** [comment]
I've also encountered this problem and gotten the same error (same quiz).
